import {
  faTwitter,
  faInstagram,
  faGooglePlus,
  faFacebook,
  faLinkedinIn
} from '@fortawesome/free-brands-svg-icons'
import {
  faStar as anotherfaStar,
  faClock as anotherFaClock
} from '@fortawesome/free-regular-svg-icons'
import {
  faAppleWhole,
  faArrowLeft,
  faArrowRight,
  faAward,
  faBagShopping,
  faBowlFood,
  faBurger,
  faCake,
  faCarrot,
  faClock,
  faFish,
  faGift,
  faHeart,
  faIceCream,
  faLocationDot,
  faMagnifyingGlass,
  faMartiniGlassCitrus,
  faMinus,
  faPhone,
  faPizzaSlice,
  faPlus,
  faSeedling,
  faStar,
  faStarHalfStroke,
  faTruck,
  faUser,
  faXmark
} from '@fortawesome/free-solid-svg-icons'

export const iconsMap = {
  bagShopping: faBagShopping,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  starFull: faStar,
  starEmpty: anotherfaStar,
  starHalf: faStarHalfStroke,
  phone: faPhone,
  burger: faBurger,
  pizza: faPizzaSlice,
  beverages: faMartiniGlassCitrus,
  iceCream: faIceCream,
  vegetables: faCarrot,
  fruit: faAppleWhole,
  dessert: faCake,
  sushi: faFish,
  soups: faBowlFood,
  salad: faSeedling,
  personal: faUser,
  map: faLocationDot,
  delivery: faTruck,
  award: faAward,
  bonuses: faGift,
  heart: faHeart,
  search: faMagnifyingGlass,
  plus: faPlus,
  minus: faMinus,
  clockFull: faClock,
  clockEmpty: anotherFaClock,
  twitter: faTwitter,
  instagram: faInstagram,
  googlePlus: faGooglePlus,
  facebook: faFacebook,
  linkedin: faLinkedinIn,
  x: faXmark
}
